### ISSUE TITLE
NumEmptyPVFailures_value when resolving MCF

### ISSUE THREAD

**Issue by edumorlom** [datacommonsorg/data#14]
After trying to write to the KG using the following configuration:
![image](https://user-images.githubusercontent.com/11444894/84351588-aed0a500-ab89-11ea-843b-3577ed4f90f8.png)

I see the following error in the logs saying: **NumEmptyPVFailures_value** and **NumSanityCheckPVFailures**.

![image](https://user-images.githubusercontent.com/11444894/84351410-55687600-ab89-11ea-811e-da0d15835fa8.png)

What does this mean?

**Comment by edumorlom** [comment]
This issue occurs when you have empty cells in your CSV file.
There are two workarounds:
1. Get rid of the empty cells. What is causing your empty cells?

2. Follow these steps (credits go to Tiffany and Jay)
a) https://screenshot.googleplex.com/gLsx8aiAn54 _(This step will fail, but it's expected. MCF will be generated)._
b) https://screenshot.googleplex.com/ooLHkFDgQto _(2 files as input)_
c) https://screenshot.googleplex.com/vRTWdsu9pVC _(2 files as input)_

**Comment by wh1210** [comment]
This is really helpful and common to come across!

**Comment by tjann** [comment]
Clarification on 2a) "This step will fail" -- while true, make sure the expected failure is this: 
![Significant number of PVs failed](https://user-images.githubusercontent.com/18621425/87102671-6a2b3e80-c207-11ea-9e80-36eee7c3346a.png). If you get another error, then do not proceed to 2b).

It is also good to check that the MCF successfully generated.

**Comment by fpernice-google** [comment]
As a further clarification, on step 2, one should check only the "Simple resolver (under 500MB)"  box, and no others.
