### ISSUE TITLE
Duplicate Observations after resolved MCF validation

### ISSUE THREAD

**Issue by edumorlom** [datacommonsorg/data#17]
After validating my Harvard Covid data, I saw 100% duplicate observations on the Validation Dashboard. I know this is an issue. Does anyone know what to do? How to fix this? Where to look at?

**My Statistical Variables are as follows:**
Node: dcid:HarvardCOVID19IncrementalCases
typeOf: dcs:StatisticalVariable
populationType: dcs:MedicalTest
statType: dcs:measuredValue
measuredProperty: dcs:incrementalCount
medicalStatus: dcs:ConfirmedCase
measurementMethod: dcs:dcDerivedStat/HarvardCOVID19

Node: dcid:HarvardCOVID19IncrementalDeaths
typeOf: dcs:StatisticalVariable
populationType: dcs:MedicalTest
statType: dcs:measuredValue
measuredProperty: dcs:incrementalCount
medicalStatus: dcs:PatientDeceased
measurementMethod: dcs:dcDerivedStat/HarvardCOVID19

![image](https://user-images.githubusercontent.com/11444894/84353414-1805e780-ab8d-11ea-9300-419eb0ce0314.png)

**Comment by wh1210** [comment]
I got same issue here. I asked Tiffany last night, she told me we can look up in BigQuery first to see if anything wrong.

**Comment by tjann** [comment]
If you're at 100%, it should be fast to just look at the resolved MCF to find Observations that only differ by value.

**Comment by edumorlom** [comment]
The two nodes are duplicates if they contain the **same body, regardless of the names**.
Even though they differ by name, the body is identical which makes them duplicates.
To fix this issue, you must introduce a new property to your statistical variables.
That is, in this case, I added the **medicalStatus** property with different values to make the two nodes different from each other.

See below for an updated example:

Node: dcid:HarvardCOVID19IncrementalCases
typeOf: dcs:StatisticalVariable
populationType: dcs:MedicalTest
statType: dcs:measuredValue
measuredProperty: dcs:incrementalCount
**medicalStatus: dcs:ConfirmedCase**
measurementMethod: dcs:dcDerivedStat/HarvardCOVID19

Node: dcid:HarvardCOVID19IncrementalDeaths
typeOf: dcs:StatisticalVariable
populationType: dcs:MedicalTest
statType: dcs:measuredValue
measuredProperty: dcs:incrementalCount
**medicalStatus: dcs:PatientDeceased**
measurementMethod: dcs:dcDerivedStat/HarvardCOVID19
