### ISSUE TITLE
Typo in Gini Index Economic Activity Statistical Variable

### ISSUE THREAD

**Issue by edumorlom** [datacommonsorg/data#326]
While doing some Statistical Variable Research for the new poverty dashboard, @jeffreyoldham and I noticed that there is a typo in the statistical variable.

GiniIndex_EcconomicActivity should be GiniIndex_EconomicActivity. There are two ccs in Economic.

https://datacommons.org/tools/timeline#place=country%2FNGA&statsVar=GiniIndex_EcconomicActivity

Tagging for visibility: @pradh @tjann

**Comment by tjann** [comment]
Thanks, assigning to me

**Comment by edumorlom** [comment]
Thanks for fixing @tjann 
closing.
