### ISSUE TITLE
[eia] add better names / descriptions

### ISSUE THREAD

**Issue by beets** [datacommonsorg/data#460]
https://autopush.datacommons.org/tools/timeline#place=geoId%2F06%2CgeoId%2F26&statsVar=Annual_Average_HeatContent_Coal_For_CommercialAndInstitutional&chart=%7B%22consumption%22%3Afalse%2C%22cost%22%3Afalse%7D

it's unclear from the name that it only applies to coal. we should revisit all the coal variables, at least. and add descriptions where we can. would be best if we could link back to EIA for the definition

cc @pradh

**Comment by beets** [comment]
here are other examples:
https://autopush.datacommons.org/tools/timeline#place=geoId%2F06%2CgeoId%2F26&statsVar=Annual_Consumption_Coal_ElectricPower&chart=%7B%22consumption%22%3Afalse%2C%22cost%22%3Afalse%2C%22heatContent%22%3Afalse%7D
https://autopush.datacommons.org/tools/timeline#place=geoId%2F06%2CgeoId%2F26&statsVar=Quarterly_Average_Cost_Coal_ElectricPower&chart=%7B%22consumption%22%3Afalse%7D
https://autopush.datacommons.org/tools/timeline#place=geoId%2F06%2CgeoId%2F26&statsVar=Annual_Consumption_Coal_ElectricPower&chart=%7B%22consumption%22%3Afalse%2C%22cost%22%3Afalse%2C%22heatContent%22%3Afalse%7D

**Comment by beets** [comment]
cc @n-h-diaz

**Comment by hareesh-ms** [comment]
Tracked in internal bug.
