### ISSUE TITLE
[un energy] stat var names

### ISSUE THREAD

**Issue by beets** [datacommonsorg/data#518]
There are a few stat vars where the names could be clarified, e.g.

https://datacommons.org/browser/Annual_Generation_Energy_Bagasse
The name is Annual Generation of Bagasse -- should it be Annual Generation of Energy from Bagasse
Perhaps the description could also be clarified, since it now read as Bagasse is being generated, not energy.

https://datacommons.org/browser/Annual_Consumption_Energy_ElectricityGeneration_Heat_FuelTransformation
The name and description here is also confusing, since it mentions both consumption and generation. Is it referring to Heat generated by Fuel Transformation consumed for Electricity Generation

Sorry these were missed during the reviews..

**Comment by ajaits** [comment]
Thanks for pointing this out.

Prashanth indicated that the population type is dropped when the name is auto generated. 

I'll update the scripts to generate names as well.

**Comment by hareesh-ms** [comment]
Tracked in internal bug.
