### ISSUE TITLE
Breaking subject table tests

### ISSUE THREAD

**Issue by Abilityguy** [datacommonsorg/data#585]
Changes brought in #526 have broken `scripts/us_census/acs5yr/subject_tables/subject_table_test.py`

**Comment by sharadshriram** [comment]
This issue is resolved in PR #592

**Comment by Abilityguy** [comment]
PR #598 excluded a few subject tables from the subject table test.

The test input size should be reduced for the following subject tables
- [ ] S0701
- [ ] S0701PR
- [ ] S0902
- [ ] S1201
- [ ] S1810
- [ ] S2601A
- [ ] S2601APR
- [ ] S2602
- [ ] S2602PR
- [ ] S2603

**Comment by sharadshriram** [comment]
- [X] S0902 is ready

**Comment by rbhoot** [comment]
S1810, S0701, S0701PR, S2601A, S2601APR, S2602, S2602PR, S2603 fixed in https://github.com/datacommonsorg/data/pull/605

**Comment by Abilityguy** [comment]
Thanks for the fixes. Closing this issue.
