### ISSUE TITLE
Tracking issue for importing Building dataset: CBECS

### ISSUE THREAD

**Issue by ajaits** [datacommonsorg/data#593]
Source: https://www.eia.gov/consumption/commercial/

1-Pager: https://docs.google.com/document/d/1yTughxNoqEzHeT7L26lyTI8STb2M3lXDDt6vD0uHcRQ/edit#

**Comment by hareesh-ms** [comment]
Commercial Buildings Energy Consumption Survey (CBECS)  imported.
