### ISSUE TITLE
[US census] Update "gender" to "sex" 

### ISSUE THREAD

**Issue by beets** [datacommonsorg/data#606]
https://www.census.gov/topics/population/age-and-sex/about.html
https://www.census.gov/library/stories/2021/08/household-pulse-survey-updates-sex-question-now-asks-sexual-orientation-and-gender-identity.html

https://datacommons.org/browser/gender

We use the term "gender" for US Census related properties. In their surveys, they refer to biological sex, and not the social construct.

**Comment by hareesh-ms** [comment]
Tracked in internal bug.
