### ISSUE TITLE
[Employment Schema] Poorly curated constraint property pairs

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/data#646]
These are pairs of constraint properties that represent very similar concepts, and yet, are modeled separately, and when they co-occur in the same StatVar cause much confusion (especially in the StatVar Hierarchy).

1. employment vs. employmentStatus:  The latter is supposed to represent labor-force, except some imports misuse it as "employment".  We should modify SVs that misuse (there are legacy popobs ones too), and rename employmentStatus to laborForceStatus.
 
2. workerStatus vs. workerClassification:  The former just says Worker/Nonworker, and the latter classifies them in a finer way. We should probably get rid of workerStatus, and include the "Nonworker" in workerClassification.

3. workStatus vs. workExperience vs. workPeriod:  The first one represents whether worker worked in the last year, or not (and also misused with number of workers in Household).  The second one, which only represents full-time work or not. The third one represents the quantity worked (N weeks).  Perhaps we should fold workExperience into workStatus and call it recentWorkStatus or something.  And rename workPeriod to quantityWorked, or something more precise.

A useful query to list the constraint values and SVs that a cprop shows up in is [here](https://console.cloud.google.com/bigquery?sq=429015563165:5fb027e8c1204483a204b6c9b515e2f9).

**Comment by hareesh-ms** [comment]
Tracked in internal bug
