### ISSUE TITLE
[Superfund]: Github checks failing

### ISSUE THREAD

**Issue by Abilityguy** [datacommonsorg/data#650]
The `test_e2e (us_epa.superfund.site_and_funding_status.process_sites_test.ProcessTest)` test seems to be failing for PR #648

Build [Link](https://pantheon.corp.google.com/cloud-build/builds/2ff618b5-4faa-4bc7-94b7-d8c7de546cef;step=1?project=datcom-ci)

**Comment by sharadshriram** [comment]
@shifucun , The build error points to the `KeyError: 'placeCoordinates'`. This error is when we resolve location of superfund sites specified through latitude and longitude. Is there a change in the `recon` API's response?

**Comment by shifucun** [comment]
Do you have a specific REST API url for this query?

**Comment by sharadshriram** [comment]
The specific url I have used in the script is  `"https://autopush.recon.datacommons.org/coordinate/resolve"` [reference](https://github.com/datacommonsorg/data/blob/master/scripts/us_epa/util/superfund_helper.py#L22)

**Comment by Abilityguy** [comment]
@shifucun Thanks for the fix. 
The tests are now passing.
Closing this issue.
