### ISSUE TITLE
[New Import] RFF Wildfire / Smoke / Drought dataset

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/data#851]
One pager with schema from Hannah (edited by shanth):
https://docs.google.com/document/d/1tBhMV0CKqekUu0gqv6F1WHeKyuQB9447/edit?resourcekey=0-9LRtU0nDxA9gCsznVsov5A#heading=h.gjdgxs

**Comment by hareesh-ms** [comment]
Tracked in internal bug
